### ISSUE TITLE
ffmpeg run command not working

### ISSUE THREAD

**Issue by itagit** [neurospeech/xamarin-android-ffmpeg#1]
first thanks a lot for your effort , this is a great work, and it will help a lot
i tried to use your component.
i installed it from NuGet, and i tried to use your sample code , or even just send a -version command , 
but i am always getting the below error. 
"WARNING: linker: /data/data/ffmpegtest.ffmpegtest/files/ffmpeg has text relocations. This is wasting memory and prevents security hardening. Please fix."

i am new to Android and ffmpeg , so any help will be great , i tried looking for a fix but from what i understand it is something related to the compiled version of the ffmpeg in NDK.
## below is the code i used

 public async System.Threading.Tasks.Task<string> version(Action<string> logger = null,
             Action<int, int> onProgress = null)
        {
            string ver = "";
            int total = 0, current = 0;
            string cmdParems = "-version";
            await FFMpeg.Xamarin.FFMpegLibrary.Run(
                _context,
                 cmdParems
                , (s) =>
                {
                    ver = s;
                    logger?.Invoke(s);
                    int n = Extract(s, "Duration:", ",");
                    if (n != -1)
                    {
                        total = n;
                    }
                    n = Extract(s, "time=", " bitrate=");
                    if (n != -1)
                    {
                        current = n;
                        onProgress?.Invoke(current, total);
                    }
                });

```
        return ver;

    }
    public void trim (string inputfile,string outputfile, Action<string> logger = null,
         Action<int, int> onProgress = null)
    {
        int total = 0, current = 0;
        string cmdParems = "-ss 00:00:01 -i " + inputfile + " -to 00:00:10 -c copy -copyts " + outputfile;
         FFMpeg.Xamarin.FFMpegLibrary.Run(
            _context,
             cmdParems
            , (s) =>
            {
                logger?.Invoke(s);
                int n = Extract(s, "Duration:", ",");
                if (n != -1)
                {
                    total = n;
                }
                n = Extract(s, "time=", " bitrate=");
                if (n != -1)
                {
                    current = n;
                    onProgress?.Invoke(current, total);
                }
            });
    }
```

---

please advice , 
thanks

**Comment by neurospeech** [comment]
Please make sure you have updated your code to Latest version. Also, this does not work yet on X86 based emulators, because the ffmpeg attached is compiled for arm processor, so this library will only work on actual device.

I am currently writing a "Light", version which will automatically download appropriate ffmpeg's latest version, based on cpu type and you will be able to test ffmpeg on emulator.

For now, just try to execute on real android device.

**Comment by neurospeech** [comment]
Please try latest version, this version is very small, however, it does download ffmpeg from raw.githubusercontent.com first time when used. For next time, it will reuse existing downloaded version.

You can customize by setting FFMpegLibrary.Instance.CDN to download content from your CDN which can fetch file from Github's url.
