### ISSUE TITLE
How to rotate videos with Xamarin.Android.MP4Transcoder?

### ISSUE THREAD

**Issue by nunohorta** [neurospeech/xamarin-android-ffmpeg#12]
Hi

Is it possible to rotate videos with the MP4Transcoder? Not changing the orientation metadata, but actually rotating the video. This was fairly simple with ffmpeg but now that we shouldn't be using it with Android 6+ I'm looking for an alternative. Thanks

**Comment by neurospeech** [comment]
This library uses https://github.com/ypresto/android-transcoder, you could ask them to create option of rotating then we can include it in our library. Transcoding entirely in .NET is slow, so we are relaying calls to native java library.

**Comment by nunohorta** [comment]
I'll give it a try, thanks!
