### ISSUE TITLE
MP4Transcoder not compatible with monoandroid71

### ISSUE THREAD

**Issue by misiekch** [neurospeech/xamarin-android-ffmpeg#19]
Cannot install MP4Transcoder via NuGet:

_Package Xamarin.Android.MP4Transcoder 1.0.9 is not compatible with monoandroid71 (MonoAndroid,Version=v7.1). Package Xamarin.Android.MP4Transcoder 1.0.9 supports: net (.NETFramework,Version=v0.0)_

Is there a way to get around this?

**Comment by BurritoSmith** [comment]
I'm having the same issue.  Were you able to solve this @misiekch ?

**Comment by misiekch** [comment]
I downloaded latest version of ffmpeg library from https://github.com/bravobit/FFmpeg-Android and added it manually (not via NuGet) to android project.

**Comment by BurritoSmith** [comment]
@misiekch  pardon my ignorance but I'm brand new to xamarin development.  I usually work in Android Studio.  The project you linked above would be easy to pull down via gradle, but how do I incorporate that into a Xamarin-Android project?  I downloaded it and don't see a jar that I can use to create a bindings library.  I'm a little lost how to import that into visual studio.

**Comment by neurospeech** [comment]
FFMpeg is not compatible with Android 5 +, so if you are compiling with platforms above lollipop, ffmpeg itself will not work, this library cannot do anything to avoid that.

**Comment by BurritoSmith** [comment]
@neurospeech I realize we shouldn't have hijacked your project thread referring to another project but your statement about ffmpeg not working is not true.  I ended up spending most of my day yesterday writing a c# wrapper around the the versions of ffmpeg that could be downloaded from the project that @misiekch  referenced above.  I'm running Oreo on my phone and I was able to compress videos with it just fine.  I didn't end up using any of the code from that other project, just the ffmpeg files included in their repo and, at least the ARM one works.

**Comment by ackava** [comment]
@BurritoSmith FFMpeg is supported if target SDK is less than 6.0 but otherwise there were issues when this libraries were created, I will check new updates soon. Also that is the reason I have added another package `Xamarin.MP4Transcoder` which replaces ffmpeg and uses native MP4 transcoding provided in Android SDK.
