### ISSUE TITLE
Include FFMpeg in install

### ISSUE THREAD

**Issue by Kragrathea** [neurospeech/xamarin-android-ffmpeg#21]
I need to be able to run my app when the user is offline. Is there any way to include the ffmpeg binary in the apk and not have to do the download from the CDN? I understand that it should only do it once. But my users are going to be **offline** when they run my app. 

I am curious why it is downloaded at runtime?  Aside from the complexity, isn't that a potential security problem

**Comment by neurospeech** [comment]
The reason we choose to download on first run is, ffmpeg binaries 30mb+, so
any change in your tiny app will always require huge publishing and
distributing network usage.

**Comment by Kragrathea** [comment]
I guess that makes sense. For my case I will have to live with the file size. I think I can see how to modify it to use local binaries. 

Thanks for the quick response!
