### ISSUE TITLE
How can I review logs of done operations?

### ISSUE THREAD

**Issue by coolhunter33** [neurospeech/xamarin-android-ffmpeg#22]
After running next command:
`
await FFMpeg.Xamarin.FFmpegLibrary.Run(Forms.Context, cmd);
`
How could I review FFMpeg logs? 

I've tried to add:
`2> logTest.txt` or `FFREPORT=file=ffreport.log:level=32` but still can't find any log info (no log file is created or no additional output during the debug is shown)

**Comment by ackava** [comment]
you can pass `(s) => ReviewLog(s)` as an argument here,

```
 public Task<File> ConvertFileAsync(Context context,
            File inputFile, 
            Action<string> logger = null, 
            Action<int,int> onProgress = null)
```
