### ISSUE TITLE
compressing video process - Not working Android version 7.1+

### ISSUE THREAD

**Issue by Anbuselvankt** [neurospeech/xamarin-android-ffmpeg#23]
I used to compress the video process with the below comments, it works for up to Nougat 7.0 (API level 24), Latest Android versions stopped working. (Versions are 
Oreo | 8.1.0 | API level 27 
Oreo | 8.0.0 | API level 26
Nougat | 7.1 | API level 25 )

Package Name: Xamarin.Android.FFmpeg
Version: 1.0.32

string[] cmds = new string[] {
"-y",
"-i",
inputFilepath,
"-strict", "experimental",
"-vcodec", "libx264",
"-preset", "ultrafast",
"-crf","30", "-acodec","aac", "-ar", "44100" ,
"-q:v", "20",
"-vf",
"mp=eq2=1:1.68:0.3:1.25:1:0.96:1",
ouputFile,
};

string cmdParams = string.Join(" ", cmds);

FFMpeg.Xamarin.FFMpegLibrary.Run(Xamarin.Forms.Forms.Context, cmdParams, loggerAction);

Can you please help me on this issue?

**Comment by DanShoubridge** [comment]
Upvote. We are having the same problem as well.

**Comment by ackava** [comment]
For Android 6.0 onwards, please use MP4Transcoder as ffmpeg is not supported
