### ISSUE TITLE
Error in VideoConverter  Class

### ISSUE THREAD

**Issue by shadow111** [neurospeech/xamarin-android-ffmpeg#6]
Hello,
i have install FFmpeg using this command  Install-Package Xamarin.Android.FFmpeg
 and paste the video class on the main activity , but i have many error on those line of code 

`await FFMpeg.Xamarin.FFMpegLibrary.Run(
                contex,
                 cmdParams
                , (s) =>
                {
                    logger?.Invoke(s);
                    int n = Extract(s, "Duration:", ",");
                    if (n != -1)
                    {
                        total = n;
                    }
                    n = Extract(s, "time=", " bitrate=");
                    if (n != -1)
                    {
                        current = n;
                        onProgress?.Invoke(current, total);
                    }
            });`

**Comment by neurospeech** [comment]
What is exact error?

**Comment by movAX13h** [comment]
I got the same error (using vs 2013 ultimate, fresh xamarin, fresh xamarin-android-ffmpeg from NuGet).  Here's a screenshot... sorry it's German. It says that the await operator can only be used inside an async method and that the return type should be changed to Task<System.Threading.Tasks.Task<Java.IO.File>>

![image](https://cloud.githubusercontent.com/assets/1974959/22760556/44d17d0c-ee57-11e6-8e3f-8b8af790542e.png)

Adding async to the method solves it. Maybe the code should be updated.
The questionmarks are features of c# 6 which is not (really) available in vs 2013.

**Comment by neurospeech** [comment]
We are working on the fix, we will be uploading new version pretty soon.
