### ISSUE TITLE
src folder?

### ISSUE THREAD

**Issue by beeradmoore** [neurospeech/xamarin-android-ffmpeg#8]
Does the binding in the src folder actually do anything in the final project if you are just downloading the binaries?

**Comment by neurospeech** [comment]
That is part of old project where ffmpeg was embedded in the .dll file itself, it is no longer used. However, I have kept it if anyone wants to embed and use it instead of downloading. 

NuGet package does not include "src" and its bindings.

**Comment by beeradmoore** [comment]
All good. Was wondering why it's not referenced.
