### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by srimantillid** [neurospeech/xamarin-android-ffmpeg#9]
await FFMpegLibrary.Run(this, "ffmpeg -version", (s) =>
                {
                    Log.Info("FFMPEG Message", s);
                });

I get the message in log.

**warning ffmpeg has text relocations. This is wasting memory and prevents security hardening**

**Comment by neurospeech** [comment]
This is due to ffmpeg binary compiled by repo https://github.com/WritingMinds/ffmpeg-android-java , also it may not be able to get around this warning because ffmpeg is huge code base in "c" and native instead of Java. You can ignore it.
